[server]
ip = "127.0.0.1"
port = 3000
workers = 4

[web]
# when there's nothing to do where should we direct the user?
homepage = "http://localhost:8080/"

# authentication providers
[auth]

# Discord Authentication
# scopes: identify, email
# https://discord.com/developers/docs/topics/oauth2
# [auth.discord]
# client_id=""
# client_secret=""
