[server]
ip = "127.0.0.1"
port = 3000
workers = 4

[web]
# when redirecting, we don't want to route the user to a page that is outside our jurisdiction
homepage = "http://localhost:8080/"
# where is this instance hosted? used to generate oauth2 redirect uris
root_page = "http://localhost:3000/"

# authentication providers
[auth]
# mesaured in seconds, how long we should allow the user to log in for before expiring their request
auth_timeout = 600

# Discord Authentication
# scopes: identify, email
# https://discord.com/developers/docs/topics/oauth2
# [auth.discord]
# client_id=""
# client_secret=""
